PROJECT_NAME := Kernel
TARGET_NAME := kernel.elf
SRC := main.c io.c serial.c

PRECOMPILED_OBJ := kernel.ld

# define PROJECT_NAME, SRC and TARGET_NAME before including cproj.mak!!!
include $(BS_ROOT)/cproj.mak
