name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install tools
        run: sudo apt-get install -y nasm clang lld
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          cp Kernel/kernel.elf ./
          cp Bootloader/bootldr.efi ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wheatley
          path: |
            build/kernel.elf
            build/bootldr.efi
